version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - node -v
      - npm -v
      - npm install
      
  build:
    commands:
      - npm run build

artifacts:
  files:
    - build/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
